[package]
name = "utf16-lit-dependabot-fails"
version = "0.1.0"
authors = ["robin <robin@harfanglab.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utf16_lit = "1"
